### ISSUE TITLE
Pebble bug

### ISSUE THREAD

**Issue by RomanistHere** [espruino/BangleApps#1046]
https://github.com/espruino/BangleApps/tree/master/apps/pebble - not sure where to submit things like that.

### Description

White bar at the top of the screen.

<div style="display: flex">
<img src="https://user-images.githubusercontent.com/49812531/145426637-adb46004-8f28-45eb-bc8d-19b1adaf0831.png" width=40%>
<img src="https://user-images.githubusercontent.com/49812531/145426649-1dc14e1a-e7b4-47cf-8f18-0b86bd0ffc64.png" width=40%>
</div>

### Steps to reproduce

Accidentally happening both at the app and when set as default clock.

### Thoughts

1. Probably other app interfering
2. Just a bug

### How to resolve

If it's because of another app, probably should "margin-top", so this top bar will always be visible or increase "z-index" to be always non-overlayble.

**Comment by gfwilliams** [comment]
Thanks! It's great having some shots of the issue. Hopefully fixed now!

**Comment by RomanistHere** [comment]
It's not fixed - I just installed it. 

P.S. Got my watch today, very cool :)

**Comment by gfwilliams** [comment]
Did you use the development app loader? Because banglejs.com/apps doesn't update immediately

**Comment by RomanistHere** [comment]
Not familiar yet, will check dev version and update the status here. Thanks for the responding :)
