### ISSUE TITLE
Flow app does not work on bangle1.

### ISSUE THREAD

**Issue by Ronin0000** [espruino/BangleApps#1053]
@TheGLander When I launch the flow app on my  bangle.js 1 there is just a bunch of colored lines going across the screen.

**Comment by gfwilliams** [comment]
I picture would be handy, but it is possible it's to do with your watch firmware. There was an issue on 2v10 I think where 3 bit images weren't rendered right (they were all stripey) - cutting edge (or 2v11 when released) will be better

**Comment by Ronin0000** [comment]
Here is a picture and I have 2v11 firmware. Sorry for the bad quality picture.
![WIN_20211216_16_55_37_Pro](https://user-images.githubusercontent.com/89286474/146471243-9cf89678-5946-413a-ae8d-9d1c74ca5c00.jpg)
.

**Comment by TheGLander** [comment]
I experienced it on the Bangle.js 1 web emulator, but it worked on my genuine Bangle.js, which I believe wasn't on the latest version (I think some version of 2v11). I think it's an artifact of `Bangle.setLCDMode("120x120")` which I need to use for collision checking. I am pretty sure it's a thing I can't fix, sorry. Probably something firmware related, as Gordon said.

**Comment by thyttan** [comment]
Candidate for being closed - leave a comment if you object!

Rationale:
Old issue which I suspect probably have been resolved by one of the subsequent FW updates.

**Comment by gfwilliams** [comment]
Just had a quick try installing Flow on 2v14 and it seems the problem still exists, so I guess this needs looking into more
